---
- name: Install Neutron Service
  apt: name={{item}} state=present
  with_items:
          - neutron-server
          - neutron-plugin-ml2
          - python-neutronclient

- name: Locate service tenant id
  shell: "keystone tenant-get service | awk '/ id / {print $4}'"
  register: service_tenant_id
  environment:
          OS_SERVICE_TOKEN: '{{neutron_bootstrap_token}}'
          OS_SERVICE_ENDPOINT: 'http://controller:35357/v2.0'         

- name: Configure Neutron
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf
  notify: restart neutron service

- name: Configure Neutron ML2 plugin
  template: src=ml2_conf.ini.j2 dest=/etc/neutron/plugins/ml2/ml2_conf.ini
  notify: restart neutron service

- name: Restart Neutron
  service: name=neutron-server state=restarted

- name: Create neutron user
  command: 'keystone user-create --name={{neutron_user_name}} --pass={{neutron_password}} --email={{neutron_email}}'
  args:
          creates: /root/.neutron_provisioning
  environment:
          OS_SERVICE_TOKEN: '{{neutron_bootstrap_token}}'
          OS_SERVICE_ENDPOINT: 'http://controller:35357/v2.0'

- name: Link neutron user to admin role
  command: 'keystone user-role-add --user=neutron --tenant=service --role=admin'
  args:
          creates: /root/.neutron_provisioning
  environment:
          OS_SERVICE_TOKEN: '{{neutron_bootstrap_token}}'
          OS_SERVICE_ENDPOINT: 'http://controller:35357/v2.0'


- name: Create the neutron service
  command: 'keystone service-create --name=neutron --type=network --description="OpenStack Networking"'
  args:
          creates: /root/.neutron_provisioning
  environment:
          OS_SERVICE_TOKEN: '{{neutron_bootstrap_token}}'
          OS_SERVICE_ENDPOINT: 'http://controller:35357/v2.0'

- name: Create neutron endpoint
  shell: "keystone endpoint-create --service-id $(keystone service-list | awk '/ network / {print $2}') --publicurl http://controller:9696 --internalurl http://controller:9696 --adminurl http://controller:9696 --region RegionOne"
  args:
          creates: /root/.neutron_provisioning
  environment:
          OS_SERVICE_TOKEN: '{{neutron_bootstrap_token}}'
          OS_SERVICE_ENDPOINT: 'http://controller:35357/v2.0'         

- name: Create provisioning confirmation file for Glance
  command: touch /root/.neutron_provisioning
  args:
        creates: /root/.neutron_provisioning
